# Generated by Django 4.2.7 on 2024-02-10 05:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_ref", models.CharField(max_length=20)),
                ("created_at", models.DateField()),
                ("payment_due", models.DateField()),
                ("description", models.TextField()),
                ("payment_terms", models.IntegerField()),
                ("client_name", models.CharField(max_length=255)),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DR", "draft"), ("PA", "paid"), ("PE", "pending")],
                        max_length=255,
                    ),
                ),
                ("sender_street", models.CharField(blank=True, max_length=255)),
                ("sender_city", models.CharField(blank=True, max_length=255)),
                ("sender_postcode", models.CharField(blank=True, max_length=10)),
                ("sender_country", models.CharField(blank=True, max_length=255)),
                ("client_street", models.CharField(blank=True, max_length=255)),
                ("client_city", models.CharField(blank=True, max_length=255)),
                ("client_postcode", models.CharField(blank=True, max_length=10)),
                ("client_country", models.CharField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
    ]
