# Generated by Django 4.2.7 on 2024-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("1", "Net 1 Day"),
                    ("7", "Net 7 Days"),
                    ("14", "Net 14 Days"),
                    ("30", "Net 30 Days"),
                ],
                max_length=255,
            ),
        ),
    ]
